
[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "NumpadMultiply"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[colors]

[colors.bright]
black = "0x555555"
blue = "0x5555ff"
cyan = "0x55ffff"
green = "0x55ff55"
magenta = "0xff55ff"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.cursor]
cursor = "0x000000"
text = "0xffffff"

[colors.normal]
black = "0x000000"
blue = "0x0000aa"
cyan = "0x00aaaa"
green = "0x00aa00"
magenta = "0xaa00aa"
red = "0xaa0000"
white = "0xaaaaaa"
yellow = "0xaa5500"

[colors.primary]
background = "0xffffff"
foreground = "0x000000"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.bold_italic]
family = "Liberation Mono"
style = "Bold Italic"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "Liberation Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
title = "Alacritty"
opacity = 1.0
"decorations_theme_variant" = "Light"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 125
lines = 30

[window.padding]
x = 0
y = 0

[keyboard]
